package by.htp.jwd.command;

public enum CommandName {
	LOGINATION, INDEXVIEW, REGISTRATION, SAVEUSER, ADDNEWCARVIEW, ADDNEWCAR, ADDPRICEVIEW, ADDPRICE, ALLCARSVIEW,
	CHOOSECARVIEW, TOLOGINATIONPAGE,LOOKINGCAR
}
